config/routes.rb
Rails.application.routes.draw do
  resources :paintings

  root 'home#index'
  get 'portfolio' => 'paintings#portfolio'
  get '/the_artist' => 'static_pages#the_artist'
  get '/guestbook' => 'static_pages#guestbook'

end

app/models/painting.rb
class Painting < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_painting, only: [:show, :edit, :update, :destroy]

  # GET /paintings
  # GET /paintings.json
  def index
    @paintings = Painting.all
  end

  def portfolio
    @horizontal_paintings = Painting.where(vertical: false)
    @vertical_paintings = Painting.where(vertical: true)
  end

  # GET /paintings/1
  # GET /paintings/1.json
  def show
  end

  # GET /paintings/new
  def new
    @painting = Painting.new
  end

  # GET /paintings/1/edit
  def edit
  end

  # POST /paintings
  # POST /paintings.json
  def create
    @painting = Painting.new(painting_params)

    respond_to do |format|
      if @painting.save
        format.html { redirect_to @painting, notice: 'Painting was successfully created.' }
        format.json { render :show, status: :created, location: @painting }
      else
        format.html { render :new }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paintings/1
  # PATCH/PUT /paintings/1.json
  def update
    respond_to do |format|
      if @painting.update(painting_params)
        format.html { redirect_to @painting, notice: 'Painting was successfully updated.' }
        format.json { render :show, status: :ok, location: @painting }
      else
        format.html { render :edit }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1
  # DELETE /paintings/1.json
  def destroy
    @painting.destroy
    respond_to do |format|
      format.html { redirect_to paintings_url, notice: 'Painting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painting
      @painting = Painting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def painting_params
      params.require(:painting).permit(:title, :description, :category, :size, :filename, :vertical)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def the_artist
  end

  def resume
  end

  def guestbook
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/home/index.html.erb
<center>
	<h1>Phyllis Neider</h1>
	<%= image_tag('not_just_roses.jpg') %>

</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phyllis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Styles -->
    <link href="http://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet" type="text/css">
    <link href="assets/css/bootstrap.css" rel="stylesheet">
    <link href="assets/css/font-awesome.css" rel="stylesheet">
    <link href="assets/css/photographer.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="assets/js/shadowbox/shadowbox.css">
</head>
<body>

 <div class="masthead clearfix">


<nav class="navbar" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a href="/"><div class="logo pull-left">Phyllis Neider</div></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/portfolio">Portfolio</a></li>
        <li><a href="/the_artist">The Artist</a></li>
        <li><a href="/Resume.pdf" target="blank">Resume</a></li>
        <li><a href="/guestbook">Guestbook</a></li>
        <li></ul>

      <ul class="nav navbar-nav navbar-right">
        <div class="socials pull-right">
        <a href="https://www.facebook.com/phyllisneiderartist"><i class="icon-facebook"></i></a> <!-- your facebook link -->
        <!--<a href=""><i class="icon-linkedin"></i></a> -->
        <a href="/guestbook"><i class="icon-envelope"></i></a> <!-- your email address -->
      </div>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


  </div>

<%= yield %>

</body>
</html>

app/views/paintings/_form.html.erb
<%= form_for(@painting) do |f| %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being saved:</h2>

      <ul>
      <% @painting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label "Painting is vertical" %>
    <%= f.check_box :vertical %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paintings/_painting.html.erb
<li class="span3" data-id="<%= painting.id %>" data-type="<%= painting.category %>">
  <a href="<%= painting.filename %>" class="thumbnail">
    <%= link_to image_tag(painting.filename.downcase), painting %>
  </a>
</li>

app/views/paintings/edit.html.erb
<h1>Editing painting</h1>

<%= render 'form' %>

<%= link_to 'Show', @painting %> |
<%= link_to 'Back', paintings_path %>

app/views/paintings/index.html.erb
<h1>Listing paintings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Category</th>
      <th>Size</th>
      <th>Filename</th>
      <th>Vertical?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paintings.each do |painting| %>
      <tr>
        <td><%= painting.title %></td>
        <td><%= painting.description %></td>
        <td><%= painting.category %></td>
        <td><%= painting.size %></td>
        <td><%= painting.filename %></td>
        <td><%= painting.vertical %></td>
        <td><%= link_to 'Show', painting %></td>
        <td><%= link_to 'Edit', edit_painting_path(painting) %></td>
        <td><%= link_to 'Destroy', painting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Painting', new_painting_path %>

app/views/paintings/new.html.erb
<h1>New painting</h1>

<%= render 'form' %>

<%= link_to 'Back', paintings_path %>

app/views/paintings/portfolio.html.erb
  
  <div class="container">
    
    <div class="clearfix">
    
    <ul class="filter-nav">
      <li class="active"><a data-id="all" href="">All</a></li>
      <li><a data-id="flowers" href="">Flowers</a></li>
      <li><a data-id="leaves" href="">Leaves</a></li>
      <li><a data-id="landscape" href="">Landscapes</a></li>
      <li><a data-id="under_the_sea" href="">Under The Sea</a></li>
      <li><a data-id="animals" href="">Animals</a></li>
      <li><a data-id="abstract" href="">Abstract</a></li>
    </ul>
    
    </div>
    
    <ul class="thumbnails" id="thumbnails">

      <%= render @horizontal_paintings %>
      <%= render @vertical_paintings %>
      
    </ul>
    
  </div>
  
  <!-- Javascript -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="assets/js/bootstrap.js"></script>
    <script type="text/javascript" src="assets/js/shadowbox/shadowbox.js"></script>
    <script type="text/javascript" src="assets/js/jquery.easing.js"></script>
    <script type="text/javascript" src="assets/js/jquery.quicksand.js"></script>
    <script src="assets/js/photographer.js"></script>

</body>
</html>

app/views/paintings/show.html.erb
<p id="notice"><%= notice %></p>

<center>
  <h1><%= @painting.title %></h1>
  <h3><%= "#{@painting.description}, #{@painting.size}" %></h3>
  <%= image_tag(@painting.filename.downcase) %>
</center>

app/views/static_pages/guestbook.html.erb
<span style="color: #000; font-weight: bold;">
  <center>
    <h1>Please email Phyllis with all inquiries:</h1>
    <h2><a href="mailto:phyllisneiderartist@gmail.com">phyllisneiderartist@gmail.com</a></h2>
  </br>


  <h3>All the paintings are for sale.
  Include your name, email address, phone number and a brief message.
  Phyllis will keep you updated on future exhibits. </h3>

  </center>
</span>

app/views/static_pages/the_artist.html.erb
<h3 style="color: #000; font-weight: bold;">Phyllis Neider is an accomplished artist in watercolor, acrylic and photography.  She received her B.F.A. in advertising design from the School of Visual & Performing Arts at Syracuse University.  Presently she studies watercolor with Linda Perlmutter, originator of the Odyssey Art at Sea Program.</h3>

<h3 style="color: #000; font-weight: bold;">She has exhibited her watercolors, acrylics and photographs in juried and solo shows throughout Westchester County, NY since 2004. Phyllis has been sharing her passion for art on Crystal Cruises through Odyssey Art at Sea since 2003. </h3>

<h3 style="color: #000; font-weight: bold;">Solo exhibits in New York include Moonbean Café, the Haven Spa, Good Food Restaurant, Club Fit Briarcliff and Club Fit Jefferson Valley, Briarcliff Manor, Warner, Ossining, Mt. Pleasant and Greenburgh Public Libraries. </h3>

<h3 style="color: #000; font-weight: bold;">Phyllis is a member of the Odyssey Art Watercolor Society, The Westchester Arts Council, Ossining Arts Council, and the Briarcliff Committee for the Arts.</h3>

<h3 style="color: #000; font-weight: bold;">Watercolor is transparent and allows her to recreate nature’s beauty through layering the paints.  She uses a vibrant palette to create bold florals and landscapes.  Her bright colors transport the viewer to a fantasy world. </h3>

<h3 style="color: #000; font-weight: bold;">Phyllis lives in Westchester County, NY with her husband Calvin. She has two grown children. </h3>